Script started on Sun 10 Sep 2023 09:09:38 PM CDT
]777;notify;Command completed;exit]0;lkillian@localhost:~/cs161/root]7;file://localhost.localdomain/home/lkillian/cs161/root[?1034h[lkillian@localhost root]$ cs[Kd ~/cs161/root
]777;notify;Command completed;cd ~/cs161/root]0;lkillian@localhost:~/cs161/root]7;file://localhost.localdomain/home/lkillian/cs161/root[lkillian@localhost root]$ ./sys161 kernel
sys161: System/161 release 1.14, compiled Sep 10 2023 16:08:46

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff <return>
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 353960433 cycles (4535903k, 18u, 349424512i)
sys161: 2059 irqs 6 exns 0r/0w disk 26r/667w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 14.152621 seconds (25.0102 mhz)
sys161: Elapsed virtual time: 14.158417320 seconds (25 mhz)
]777;notify;Command completed;./sys161 kernel]0;lkillian@localhost:~/cs161/root]7;file://localhost.localdomain/home/lkillian/cs161/root[lkillian@localhost root]$ exit
exit

Script done on Sun 10 Sep 2023 09:10:19 PM CDT
